Counter visual update
front-end-by-rimantas/25-grupe-portfolio-personal pull request #20
Opened 2021-03-31 07:01 UTC by tonyhokas113

2021-03-31 11:34 UTC, eBalciunaite commented on css/custom-home.css
> +@import './components/counter.css';
komponento importą reiktų rašyti kartu su kitais komponentais (8 eilutė), o ne tarp komentarų :)
Taip pat jie turi būti surašyti ABC tvarka, tai counteris turės būti pirmas importuojamų components sąraše.

2021-03-31 11:37 UTC, eBalciunaite requested changes
komponento importą reiktų rašyti kartu su kitais komponentais (8 eilutė), o ne tarp komentarų (18 eil) :)
Taip pat jie turi būti surašyti ABC tvarka, tai counteris turės būti pirmas importuojamų components sąraše.

2021-03-31 11:57 UTC, Darius717 approved these changes, later dismissed

2021-03-31 13:22 UTC, tonyhokas113 commented
> komponento importą reiktų rašyti kartu su kitais komponentais (8 eilutė), o ne tarp komentarų (18 eil) :)
> Taip pat jie turi būti surašyti ABC tvarka, tai counteris turės būti pirmas importuojamų components sąraše.

Bet tada kokia prasmė tų visų komentarų, kurie yra išvardinti nuo 12 eilutės custom-home.css faile? Aš maniau jog jie yra kaip place holderiai kaip ir index.html faile. Tiesiog kad žinotumėm kur ką importinti ir po to nesusimaišytumėme. :)

2021-03-31 17:10 UTC, eBalciunaite submitted a review, later dismissed

2021-03-31 17:40 UTC, Darius717 approved these changes, later dismissed

2021-04-01 06:45 UTC, eBalciunaite commented
> Bet tada kokia prasmė tų visų komentarų, kurie yra išvardinti nuo 12 eilutės custom-home.css faile? Aš maniau jog jie yra kaip place holderiai kaip ir index.html faile. Tiesiog kad žinotumėm kur ką importinti ir po to nesusimaišytumėme. :)

Nepamenu, kokia tiksliai prasmė komentarų, reiks šiandien paklausti per paskaitą :D
Kai Rimantas pasakojo apie import/export, tai rašiausi užrašus, ištrauka: "importai turi būti sudėlioti failo pradžioje. Bet yra "kliurka": JS leidžia, o CSS neleidžia importų maišyti į teksto eigą."

2021-04-01 06:46 UTC, eBalciunaite approved these changes

2021-04-01 06:46 UTC, eBalciunaite approved these changes

2021-04-01 06:48 UTC, LidijaMK approved these changes

2021-04-01 07:00 UTC, merged