Choose your plan
front-end-by-rimantas/25-grupe-portfolio-personal pull request #39
Opened 2021-04-04 19:19 UTC by Darius717

2021-04-05 14:34 UTC, LidijaMK submitted a review, later dismissed

2021-04-06 08:07 UTC, eBalciunaite requested changes
Portfolio dalies kodas neatnaujintas - neatitinka develop html faile esančio kodo.

2021-04-06 13:31 UTC, Darius717 commented
Fixed.

2021-04-07 06:51 UTC, eBalciunaite approved these changes

2021-04-07 06:53 UTC, LidijaMK approved these changes

2021-04-07 06:54 UTC, merged